### ISSUE TITLE
local-as in arista.eos.eos_bgp

### ISSUE THREAD

**Issue by mikeyrad** [ansible-collections/arista.eos#144]
SUMMARY
Unable to set local-as for neighbors in the bgp module

ISSUE TYPE
- Feature Request

COMPONENT NAME
arista.eos.eos_bgp

ADDITIONAL INFORMATION
Some bgp neighbors require different local AS numbers, ie:
```
router bgp xxxxx
    neighbor 10.10.10.1 local-as 65001 no-prepend replace-as
```

**Comment by GomathiselviS** [comment]
Hi @mikeyrad Thank you for submitting the issue. We are releasing the eos_bgp_global and eos_bgp_af (address_family) modules by the end of this month. These modules should address the above issue. I request you to use those modules going forward. Please let us know your feedback after using these modules.
