### ISSUE TITLE
arista.eos.eos_static_routes and state deleted

### ISSUE THREAD

**Issue by aamsaleg** [ansible-collections/arista.eos#159]
Hello,
I try to understand the state deleted because I have a strange behaviour, maybe it is because I don't use the option as I should.

I'm using ansible 2.9 and latest ansible-galaxy collection

Here a sample playbook, var prompts are omitted, usage explained after the code:

[playbook.txt](https://github.com/ansible-collections/arista.eos/files/5881582/playbook.txt)

Usage:
During the var prompt, I choose either add a new route (merged) or delete existing one (deleted)
Merge is ok, everything is fine, route is added.
Repeating the same playbook with same values except the state delete all the routes in all vrf.

Here a result of a deleted state:
[result.txt](https://github.com/ansible-collections/arista.eos/files/5881585/result.txt)

So my question is simple:
the deleted state is only for 1 route or all the routes because here, all ipv4 routes are removed.
If it is a normal behaviour, is there a way to remove only a specific route?

Kind regards

**Comment by GomathiselviS** [comment]
@aamsaleg The `deleted` state of the static_routes resource module will delete the entries at the `afi` level when `afi` is specified. if `afi` is not specified, all the static routes will be deleted. Inorder to delete only one route under a particular afi, please use the `replaced` state, with config as the source of truth. The route not present in the config (SoT) , will be removed .

Please let me know if you have any more questions on this module.

**Comment by aamsaleg** [comment]
Hello,
thank you for your reply.
I'll do that.
Kind regards,
Alex
