### ISSUE TITLE
Private argument spec validation methods no longer available in Ansible Core 2.11

### ISSUE THREAD

**Issue by samdoran** [ansible-collections/arista.eos#182]
##### SUMMARY
Argument spec validation has changed in Ansible Core 2.11. The following private method calls should be changed to use the public interface:

```
arista.eos/plugins/modules/eos_logging.py
414:            module._check_required_if(required_if, item)  # --> ansible.module_utils.common.validation.check_required_if()

arista.eos/plugins/modules/eos_user.py
339:        type_checker = module._CHECK_ARGUMENT_TYPES_DISPATCHER[value_type]  # --> ansible.module_utils.common.parameters.DEFAULT_TYPE_VALIDATORS

arista.eos/plugins/modules/eos_linkagg.py
274:            module._check_required_together(required_together, item)  # --> ansible.module_utils.common.validation.check_required_together()

arista.eos/plugins/modules/eos_static_route.py
207:            module._check_required_together(required_together, item)  # --> ansible.module_utils.common.validation.check_required_together()
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`arista.eos/plugins/modules/eos_linkagg.py`
`arista.eos/plugins/modules/eos_logging.py`
`arista.eos/plugins/modules/eos_static_route.py`
`arista.eos/plugins/modules/eos_user.py`

##### ANSIBLE VERSION

```paste below
2.11
```

**Comment by Qalthos** [comment]
We can't move to the new location while we support versions < 2.11, and the private attribute will persist for the foreseeable future.

I'm keeping the original issue at ansible-collections/ansible.netcommon#186 open for now to coordinate efforts around replacing it if and when that becomes feasible
