### ISSUE TITLE
SSH Keys Not Being Added with eos_user

### ISSUE THREAD

**Issue by tonybourke** [ansible-collections/arista.eos#189]
When using the eos_user module, there's an option for adding SSH keys. 

...

- name: create a new user
  arista.eos.eos_user:
    name: admin
    sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
```
```

I've tried default ansible modules, I've downloaded the latest collection from ansible-galaxy (2.0.2) and referenced arista.eos.eos_users as well. 

The ansible-playbook run appears to work, it will show however many hosts as "changed" that you ran it again, but the SSH key never shows up. I can add the same key manually via the CLI and the key works. I've also tried, instead of using lookup() just pasting the actual key into the playbook under "sshkey:", but that didn't work either. The key never gets installed, and doesn't show up in "show run" nor does it show up in the local persist or non-persist Linux file system. 

```
ansible-playbook -k -i hosts.ini add_ssh.yml
SSH password:

PLAY [all] *********************************************************************

TASK [Add user and SSH key] ****************************************************
[WARNING]: Module did not set no_log for update_password
changed: [leaf1]

PLAY RECAP *********************************************************************
leaf1                      : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

I've tried several different Ansible installs, as well as a few versions of vEOS (4.25.0F) and cEOS (4.25.1F-20001546.4251F (engineering build)).

**Comment by 33Fraise33** [comment]
I can confirm I have the same issue. When I check the command running the ansible play with verbose option this is the command being sent to the switch: 
`username <username> sshkey ssh-rsa <keycontent>`

When you enter that command on the switch you get an error: 
`% Unavailable command (This command is deprecated by 'username USERNAME ssh-key')`
when you change the command to `ssh-key` it does work.

**Comment by tonybourke** [comment]
Ah, that makes sense. There was a change in the CLI (settlement with Cisco) and some of the CLI commands have changed. I'm not sure which version it started at. 

I changed the code in the module, and sure enough it worked.
