### ISSUE TITLE
on_become Prompt Regex Pattern Issue Using Arista EOS version 4.24.4M when authenticating using Cisco ISE to enable mode

### ISSUE THREAD

**Issue by lgilroy** [ansible-collections/arista.eos#210]
##### SUMMARY
There is an issue with the prompt being sent back after I login with my user credentials and use become (enable) the prompt is showing an error. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Tested cli_command and eos_facts and both are failing.

##### ANSIBLE VERSION
```
ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/lgilroy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lgilroy/venv/ansible/lib/python3.8/site-packages/ansible
  executable location = /home/lgilroy/venv/ansible/bin/ansible
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION
Issue is the code is looking for a lower case 'p' in the password prompt and we recieve a timeout since the prompt received has an upper case p. 
Issue is at line 75 in plugins/terminal/eos.py   

Fixed it by modifying the following.
```
diff orig_eos.py eos.py
75c75
<                 r"[\r\n]?password: $", errors="surrogate_or_strict"
---
>                 r"[\r\n]?(?:.*)?[Pp]assword: ?$", errors="surrogate_or_strict"
```

##### EXPECTED RESULTS
Prompt to be returned

##### ACTUAL RESULTS
Timeout

**Comment by GomathiselviS** [comment]
@lgilroy I shall make the regex pattern for password case insensitive. Meanwhile can you please provide more details on the terminal output (the exact prompt) ?
