### ISSUE TITLE
eos_bgp_global access_group needs to be able to take both IPv4 and IPv6 groups

### ISSUE THREAD

**Issue by sc68cal** [ansible-collections/arista.eos#281]
Currently it is listed as a `dictionary` that can only take a single entry, either `ipv4` or `ipv6` - It should either be a list where two elements can be added, or the key/values changed to allow for both address families to have settings.

Example:

```
router bgp MY-ASN
   ip access-group MY-IPV4-GROUP
   ipv6 access-group MY-IPV6-GROUP
```

**Comment by GomathiselviS** [comment]
@sc68cal Thanks for submitting the issue. I shall work on providing the fix.
