### ISSUE TITLE
eos_config diff_against intended_config's after is not the applied after config

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/arista.eos#348]
##### SUMMARY

When running:

```yaml

- name: DIFF FULL CONFIGS
  arista.eos.eos_config:
    diff_against: intended
    intended_config: "{{ lookup('file', intended_config_path) }}"
  check_mode: False
  diff: True
  register: audit_config

- debug:
      msg: "intended_config: {{ lookup('file', intended_config_path) }}"

- debug:
      msg: "before: {{ audit_config['diff']['before'] }}"

- debug:
      msg: "after: {{ audit_config['diff']['after'] }}"

```

- The before & the after missing the `!` found from the `show running-config`  and `show session-config`
- The after config incorrectly shows `no shutdown` under an interface when the running config would not show that.  It looks like it is just showing the `intended_config` without actually showing the config output of `show session-config` which would reflect the true config state after applying the `intended_config`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`eos.config`

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.4]
  config file = None
  configured module search path = ['/home/rmerolle/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rmerolle/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/rmerolle/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rmerolle/.local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
4.1.2
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ubuntu 20.04

##### STEPS TO REPRODUCE

```yaml

- name: DIFF FULL CONFIGS
  arista.eos.eos_config:
    diff_against: intended
    intended_config: "{{ lookup('file', intended_config_path) }}"
  check_mode: False
  diff: True
  register: audit_config

- debug:
      msg: "intended_config: {{ lookup('file', intended_config_path) }}"

- debug:
      msg: "before: {{ audit_config['diff']['before'] }}"

- debug:
      msg: "after: {{ audit_config['diff']['after'] }}"

```

##### EXPECTED RESULTS

**intended_config:**
```bash
[..redacted for brevity]
!
interface Ethernet1
  description test
  ip address 192.168.1.1/24
  no shutdown
!
interface Ethernet2
  description test2
  ip address 10.0.1.1/24
  no shut
!
[..redacted for brevity]
```

**before:**
```bash
[..redacted for brevity]
!
interface Ethernet1
  description test
  ip address 10.0.0.1/24
  shutdown
!
interface Ethernet2
  ip address 10.0.1.1/24
!
[..redacted for brevity]
```

**after:**
```bash
[..redacted for brevity]
!
interface Ethernet1
  description test
  ip address 192.168.1.1/24
!
interface Ethernet2
 description test2
  ip address 10.0.1.1/24
!
[..redacted for brevity]
```

##### ACTUAL RESULTS

**intended_config:**
```bash
[..redacted for brevity]
interface Ethernet1
  description test
  ip address 192.168.1.1/24
  no shutdown
!
interface Ethernet2
  description test2
  ip address 10.0.1.1/24
  no shut
!
[..redacted for brevity]
```

**before:**
```bash
[..redacted for brevity]
interface Ethernet1
  description test
  ip address 10.0.0.1/24
  shutdown
interface Ethernet2
  ip address 10.0.1.1/24
[..redacted for brevity]
```

**after:**
```bash
[..redacted for brevity]
interface Ethernet1
  description test
  ip address 192.168.1.1/24
  no shutdown
interface Ethernet2
 description test2
  ip address 10.0.1.1/24
  no shutdown
[..redacted for brevity]
```

Note:
- `no shutdown` should not appear in the after config in this instance
- `!` should appear in the after config in this instance

**Comment by ryanmerolle** [comment]
Looking further into the module, the after is not actually applied to the device, hence the behavior.

This is likely by design, but still not idea.

This module seems to run in order(per my AAA accounting logs):

1. show version
2. show hostname
3. show configuration-sessions
4. show running-config

I propose that it do the following:

1. show version
2. show hostname
3. show configuration-sessions
4. show running-config
5. enter a config session
6. apply intended_config (as a replace function)
7. show sessicon-config (report that to the user as the diff['after']

**Comment by ryanmerolle** [comment]
I am not suggesting this functionality should overwrite the existing, but maybe added as a new feature.  That way, users can compare config off box using fact_diff

**Comment by GomathiselviS** [comment]
@ryanmerolle Can you please try "diff_against: session" and "diff_against: running" ? These options, do the diffs after applying the intended_config. Please let me know if these options work as you expect.

**Comment by ryanmerolle** [comment]
Hello @GomathiselviS is this supposed to work with check_mode?  It did not seem to show me.

I frankly would just want a feature like validate_intended_config where eos would apply the config as a session-config, capture the `show session-config` and exit the session-config without applying as running-config.  Then I could take a backup of the running config and diff off box.
