### ISSUE TITLE
Getting error for provider key while using some of the modules under this collection

### ISSUE THREAD

**Issue by ashishmodi2003** [ansible-collections/arista.eos#406]
##### SUMMARY
- Getting error for provider key while using some of the modules under this collection

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_interfaces, eos_l2_interfaces, eos_vlans

##### ANSIBLE VERSION
2.9

```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by rohitthakur2590** [comment]
@ashishmodi2003  these are the resource modules and do not require provider spec anymore. We have already deprecated the older modules which needed provider specs.
