### ISSUE TITLE
Current versions of arista.eos are not compatible with ansible.netcommon:5.0.x

### ISSUE THREAD

**Issue by sbyount** [ansible-collections/arista.eos#420]
##### SUMMARY
When attempting to gather facts on Arista switches with "net_version": "4.26.3M", using arista.eos:6.0.0, and ansible.netcommon:5.0.0, the task errors with:

FAILED! => {"msg": "Could not find imported module support code for ansible_collections.arista.eos.plugins.modules.eos_facts.  Looked for (['ansible_collections.ansible.netcommon.plugins.module_utils.network.common.network_template.NetworkTemplate', 'ansible_collections.ansible.netcommon.plugins.module_utils.network.common.network_template'])"}

According to the change log for netcommon in v5.0.0, "NetworkTemplate is no longer importable from ansible_collections.ansible.netcommon.plugins.module_utils.network.common and should now be found at its proper location ansible_collections.ansible.netcommon.plugins.module_utils.network.common.rm_base.network_template".

https://github.com/ansible-collections/ansible.netcommon/blob/main/CHANGELOG.rst#breaking-changes-porting-guide

ansible-netcommon:4.1.0 appears to work but I have not tested all of the eos_facts options.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
arista.eos.eos_facts

##### ANSIBLE VERSION
```
ansible [core 2.14.1]
  config file = /Users/zg46503/code/arista-avd/ansible.cfg
  configured module search path = ['/Users/uname.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/uname/code/arista-avd/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/uname/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/uname/code/arista-avd/venv/bin/ansible
  python version = 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02) [Clang 6.0 (clang-600.0.57)] (/Users/uname/code/arista-avd/venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
Collection        Version
----------------- -------
ansible.netcommon 4.1.0
ansible.utils     2.9.0
ansible.yang      1.0.0
arista.avd        3.8.4
arista.cvp        3.6.0
arista.eos        6.0.0
community.general 6.5.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
MacOS 13.4

##### STEPS TO REPRODUCE
```yaml
---
- name: get facts
  hosts: HOST_GROUP

  tasks:
  - arista.eos.eos_facts:
      gather_subset: all
```

##### EXPECTED RESULTS
Facts successfully gathered

##### ACTUAL RESULTS
Error above

**Comment by sbyount** [comment]
Any status on this?

**Comment by rohitthakur2590** [comment]
This has been fixed in latest releases.

**Comment by sbyount** [comment]
Thank you.
