### ISSUE TITLE
eos_config:Integration test issue:assertion failed

### ISSUE THREAD

**Issue by komaldesai13** [ansible-collections/arista.eos#484]
##### SUMMARY
When running ios_facts integration tests from Controller with EE container,
We get an unexpected error: Assertion failed
On task [configure hostname](https://github.com/ansible-collections/arista.eos/blob/main/tests/integration/targets/eos_config/tests/cli/config.yaml#L16C9-L16C27)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_config

##### ANSIBLE VERSION
2.14

##### COLLECTION VERSION
4.24.6

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE
Run integration eos_config test, the following task failed.
See below the actual results.

##### EXPECTED RESULTS
The task will pass with not errors.

##### ACTUAL RESULTS

TASK [/usr/share/ansible/collections/ansible_collections/arista/eos/tests/integration/targets/eos_config : configure hostname] ***
task path: /usr/share/ansible/collections/ansible_collections/arista/eos/tests/integration/targets/eos_config/tests/cli/config.yaml:16
ok: [10.0.178.253] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "after": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "config": "! Command: show running-config\\n! device: foo (vEOS, EOS-4.24.6M)\\n!\\n! boot system flash:/vEOS-lab.swi\\n!\\ntransceiver qsfp default-mode 4x10G\\n!\\nservice routing protocols model ribd\\n!\\nhostname foo\\nip name-server vrf default 1.1.1.1\\ndns domain ansible.test\\n!\\nspanning-tree mode mstp\\n!\\nno aaa root\\n!\\nusername admin privilege 15 role network-admin secret sha512 $6$Dq3slCu4l7sO/kMX$D97XDK3fxD9OYFyKcw7/YBZnaGtABzJSS8JAeqOYfibnCJcMns21U3MYCwX6LUO.NoZOx.zY4Sb7bD0Hq8ImQ0\\nusername ansible secret sha512 $6$Q6sPqQHMxteOgkl1$CU815VuqE1ddO9VVpWa1PtlrIM.4oHc7V80fD89zLSzY4nEqVcPfWmq6KTcpHfs9sWZW2T2trBXP5ZIDvu09X1\\nusername zuul privilege 15 nopassword\\nusername zuul ssh-key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDI3XA0A84nUpCr9mfkrDjBdoNFtYMXqXMm2+WsGrOJUA2ESodUDDfTKmsA/xEygdCnj8JfSC3SYhc0uKHVe0RdG20mzntUqD50kB0STFeOHh3ee7FXmMxcLqLlyY9pJkn1V5WOi/D1Lbz8MwRUVBfqufryavwHla/9CPuAtPcut8mTUB0+Rapnv8W3n4dA6PqHNW1tylJUXj6P4trJPnFrdfMaIxc21tfd/QrMM4h90phW3zNILE0qF9UHpQxP0zew/LcD9rc+IhnbgC3DeCQDyiqJOsJRDo58RuwWmQHCF0SfiFQJ4qwrc6TFSJqSdi2aRY0S/vRMbXkD+6Hg2KWQyz6Z6EpY7RARletqJwNnzuuhXr2HSCj5QALe+0U/aUEX+dnydYBX6Nqa+0Rz/qV5aUk4YP1C2/dBCAdbYXPotBT6QBfekE428mJV8Mr7G/M7kwZ8v9WjytyJ8/FYNuekYDWonk6QTwDgQhMTiQI3Yxnu3ID63BL959lfUIv96bsifVI6/D36KTAdFi/dl7Omn5MZ9A5JXA7l+yEJKf4pcPTpQcPbjGSKyaPu0uffEjV9CTr3+VMwzq1uenxGDQ9cT/ud4pEEjwU/ihr6yttouTCvDu9ydrflHljUXxf+X00NW7HkrHnvS43AGnxQzi9g2lTOC9yDlDGbQjmnVjec7w== zuul-executor\\n!\\ninterface Ethernet1\\n   no switchport\\n!\\ninterface Ethernet2\\n   description this is a test\\n   shutdown\\n   no switchport\\n!\\ninterface Management1\\n   ip address dhcp\\n   dhcp client accept default-route\\n!\\nip routing\\n!\\nend",
            "defaults": false,
            "diff_against": "session",
            "diff_ignore_lines": null,
            "intended_config": null,
            "lines": [
                "hostname foo"
            ],
            "match": "line",
            "parents": null,
            "replace": "line",
            "running_config": "! Command: show running-config\\n! device: foo (vEOS, EOS-4.24.6M)\\n!\\n! boot system flash:/vEOS-lab.swi\\n!\\ntransceiver qsfp default-mode 4x10G\\n!\\nservice routing protocols model ribd\\n!\\nhostname foo\\nip name-server vrf default 1.1.1.1\\ndns domain ansible.test\\n!\\nspanning-tree mode mstp\\n!\\nno aaa root\\n!\\nusername admin privilege 15 role network-admin secret sha512 $6$Dq3slCu4l7sO/kMX$D97XDK3fxD9OYFyKcw7/YBZnaGtABzJSS8JAeqOYfibnCJcMns21U3MYCwX6LUO.NoZOx.zY4Sb7bD0Hq8ImQ0\\nusername ansible secret sha512 $6$Q6sPqQHMxteOgkl1$CU815VuqE1ddO9VVpWa1PtlrIM.4oHc7V80fD89zLSzY4nEqVcPfWmq6KTcpHfs9sWZW2T2trBXP5ZIDvu09X1\\nusername zuul privilege 15 nopassword\\nusername zuul ssh-key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDI3XA0A84nUpCr9mfkrDjBdoNFtYMXqXMm2+WsGrOJUA2ESodUDDfTKmsA/xEygdCnj8JfSC3SYhc0uKHVe0RdG20mzntUqD50kB0STFeOHh3ee7FXmMxcLqLlyY9pJkn1V5WOi/D1Lbz8MwRUVBfqufryavwHla/9CPuAtPcut8mTUB0+Rapnv8W3n4dA6PqHNW1tylJUXj6P4trJPnFrdfMaIxc21tfd/QrMM4h90phW3zNILE0qF9UHpQxP0zew/LcD9rc+IhnbgC3DeCQDyiqJOsJRDo58RuwWmQHCF0SfiFQJ4qwrc6TFSJqSdi2aRY0S/vRMbXkD+6Hg2KWQyz6Z6EpY7RARletqJwNnzuuhXr2HSCj5QALe+0U/aUEX+dnydYBX6Nqa+0Rz/qV5aUk4YP1C2/dBCAdbYXPotBT6QBfekE428mJV8Mr7G/M7kwZ8v9WjytyJ8/FYNuekYDWonk6QTwDgQhMTiQI3Yxnu3ID63BL959lfUIv96bsifVI6/D36KTAdFi/dl7Omn5MZ9A5JXA7l+yEJKf4pcPTpQcPbjGSKyaPu0uffEjV9CTr3+VMwzq1uenxGDQ9cT/ud4pEEjwU/ihr6yttouTCvDu9ydrflHljUXxf+X00NW7HkrHnvS43AGnxQzi9g2lTOC9yDlDGbQjmnVjec7w== zuul-executor\\n!\\ninterface Ethernet1\\n   no switchport\\n!\\ninterface Ethernet2\\n   description this is a test\\n   shutdown\\n   no switchport\\n!\\ninterface Management1\\n   ip address dhcp\\n   dhcp client accept default-route\\n!\\nip routing\\n!\\nend",
            "save_when": "never",
            "src": null
        }
    }
}

TASK [/usr/share/ansible/collections/ansible_collections/arista/eos/tests/integration/targets/eos_config : ansible.builtin.assert] ***
task path: /usr/share/ansible/collections/ansible_collections/arista/eos/tests/integration/targets/eos_config/tests/cli/config.yaml:23
fatal: [10.0.178.253]: FAILED! => {
    "assertion": "result.changed == true",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}

**Comment by rohitthakur2590** [comment]
@komaldesai13 I would check my startup-config or initial running-config and make sure that the hostname is not configured.
