### ISSUE TITLE
eos_snmp_server

### ISSUE THREAD

**Issue by bradh1977** [ansible-collections/arista.eos#487]
##### SUMMARY

rendered configuration is incorrect for Arista EOS version 4.28.4M 
1. under user config line - no space between vrf & vrf name var --> snmp-server host 'hostip' vrf'vrfname' version 3 priv 'user'
        should be-> snmp-server host 'hostip' vrf 'vrfname' version 3 priv 'user
3. under host config line - omits keyword auth -> snmp-server user user1 group1 v3  sha sha-pass priv aes aes-pass
        should be-> snmp-server user 'user1' 'group1' v3 auth sha 'sha-pass' priv aes 'aes-pass'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

arista.eos.eos_snmp_server

##### ANSIBLE VERSION

```paste below
Ansible version 2.13.7
```

##### COLLECTION VERSION

community.general 2.5.1

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Arista EOS 4.28.4M

##### STEPS TO REPRODUCE

---
- name: Configure SNMPv3 on Arista EOS Switches
  hosts: veos
  tasks:
    - name: Set SNMPv3 parameters vrf mgmt VRF
      arista.eos.eos_snmp_server:
        config:
          contact: "admin"
          location: "location1"
          vrfs: 
            - vrf: "management"
              local_interface: "Management1"
          groups:
            - group: "group1"
              auth_privacy: "priv"
              version: "v3"
          users:
            - user: "user1"
              group:  "group1"
              version: "v3"
              auth: 
                algorithm: "sha"
                auth_passphrase: "shaPassword1"
                encryption: "aes"
                priv_passphrase: "aesPassphrase123"
          hosts:
            - host: "10.10.10.11"
              vrf: "management"
              version: "3 priv"
              user: "user1"
            - host: "10.10.10.10"
              vrf: "management"
              version: "3 priv"
              user: "user1"   
    - name: Save configuration
      arista.eos.eos_command:
        commands:
          - "write memory"

##### ACTUAL RESULTS

```paste below

```

**Comment by bradh1977** [comment]
rendered config: 
        "snmp-server host 10.10.10.11 vrfmanagement version 3 priv user1",
        "snmp-server host 10.10.10.10 vrfmanagement version 3 priv user1",
        "snmp-server group group1 v3 priv",
        "snmp-server user user1 group1 v3 sha ******** priv aes ********",
        "snmp-server vrf management local-interface Management1",
        "snmp-server contact admin",
        "snmp-server location location"

should be 
        "snmp-server host 10.10.10.11 vrf management version 3 priv user1",
        "snmp-server host 10.10.10.10 vrf management version 3 priv user1",
        "snmp-server group group1 v3 priv",
        "snmp-server user user1 group1 v3 auth sha ******** priv aes ********",
        "snmp-server vrf management local-interface Management1",
        "snmp-server contact admin",
        "snmp-server location location1"

**Comment by TheRealBecks** [comment]
I created the PR #488

**Comment by TheRealBecks** [comment]
@bradh1977 Thanks for pointing that out (once again), I updated my PR :smiley:
