### ISSUE TITLE
httpapi uses | json command

### ISSUE THREAD

**Issue by garbled1** [ansible-collections/arista.eos#75]
##### SUMMARY

The httpapi/eos.py:get_device_info(self): routine calls show hostname | json instead of using the api method

fixed via:
'''
        #reply = self.send_request("show hostname | json")
        reply = self.send_request("show hostname", output="json")

'''

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

httpapi/eos.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/garbled/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by Qalthos** [comment]
So this is true... but it doesn't seem to be an issue on any device I have access to. Can you clarify that this is causing a failure and details of the device you're seeing it on?

**Comment by garbled1** [comment]
Basically I have a 7124SX running 4.13, which, kinda works.  I have some local hacks to make it function, which I'm seeing if I can make into a patch that is integratable, but this one in particular is, and is easily so.  (4.13, which is as high as this switch goes, doesn't have | json at all.  :( )

**Comment by Qalthos** [comment]
> Basically I have a 7124SX running 4.13, which, kinda works. I have some local hacks to make it function, which I'm seeing if I can make into a patch that is integratable, but this one in particular is, and is easily so. (4.13, which is as high as this switch goes, doesn't have | json at all. :( )

I see. We do make efforts to keep things compatible, but 4.13 is pretty old at this point, and we can't guarantee compatibility with every past version. I think that #78 has solved this issue, and hopefully your other issues are similarly addressable, but we really can't guarantee any sort of support for a version that reached end of support four years ago.
