### ISSUE TITLE
Using state=merged with lacp mode on vs. active

### ISSUE THREAD

**Issue by sc68cal** [ansible-collections/arista.eos#95]
I have the following configuration:

```
interface Port-Channel1
!
interface Port-Channel3
!
interface Port-Channel4
!
interface Ethernet1
   channel-group 1 mode on
!
interface Ethernet2
   channel-group 1 mode on
!
interface Ethernet3
   channel-group 3 mode on
!
interface Ethernet4
   channel-group 4 mode on
!
interface Ethernet5
!
```

I ran a playbook

`
changed: [testvm] => {"after": [{"members": [{"member": "Ethernet1", "mode": "on"}, {"member": "Ethernet2", "mode": "on"}], "name": "Port-Channel1"}, {"members": [{"member": "Ethernet3", "mode": "on"}], "name": "Port-Channel3"}, {"members": [{"member": "Ethernet4", "mode": "on"}], "name": "Port-Channel4"}], "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "before": [{"members": [{"member": "Ethernet1", "mode": "on"}, {"member": "Ethernet2", "mode": "on"}], "name": "Port-Channel1"}, {"members": [{"member": "Ethernet3", "mode": "on"}], "name": "Port-Channel3"}, {"members": [{"member": "Ethernet4", "mode": "on"}], "name": "Port-Channel4"}], "changed": true, "commands": ["interface Ethernet1", "channel-group 1 mode active", "interface Ethernet2", "channel-group 1 mode active", "interface Ethernet3", "channel-group 3 mode passive", "interface Ethernet4", "channel-group 4 mode passive"]}
`

However it does not appear that the config changed, even though the `commands` field had the commands that were supposed to have been run

```
interface Port-Channel1
!
interface Port-Channel3
!
interface Port-Channel4
!
interface Ethernet1
   channel-group 1 mode on
!
interface Ethernet2
   channel-group 1 mode on
!
interface Ethernet3
   channel-group 3 mode on
!
interface Ethernet4
   channel-group 4 mode on
!
```

The problem is I have never really found good documentation around `merged` vs `overridden` vs `replaced` anywhere so I don't know if this is the intended behavior for `merged`. I don't think it is, and I'm afraid to set `overridden` or `replaced` because I don't quite understand how those behave in more complex scenarios

**Comment by GomathiselviS** [comment]
@sc68cal  Can you please share the playbook you used ?

**Comment by GomathiselviS** [comment]
Hi @sc68cal , I think I know what the issue is.

Your playbook should be trying to change the mode of the channel-group from 'on' to 'active/passive'.
When I tried this on my local setup, the following error is thrown, which is not handled by the module.

```
veos(config-if-Et1)#interface Ethernet 2
veos(config-if-Et2)#channel-group 15 mode active
% Cannot change mode; remove all members and try again.
veos(config-if-Et2)#

```
Since the 'commands' is populated, changed is set as True, though the execution of these commands was not successful. That is the reason for **after = before**
I will work on fixing this issue.

For documentation, please refer [this link](https://docs.ansible.com/ansible/latest/network/user_guide/network_resource_modules.html)

**Comment by sc68cal** [comment]
> For documentation, please refer [this link](https://docs.ansible.com/ansible/latest/network/user_guide/network_resource_modules.html)

@GomathiselviS excellent, thank you for the link. Do you think we should include a link to this in the docs for each module? It would be useful...

**Comment by GomathiselviS** [comment]
@sc68cal We shall discuss about adding the link. Thanks for the suggestion.
